In [6]:
import pandas as pd
from unidecode import unidecode

In [7]:
df = pd.read_csv('hotele_raw.csv')
df.head(5)

,location_id,name,query_city,address_obj.street1,address_obj.street2,address_obj.city,address_obj.state,address_obj.country,address_obj.postalcode,address_obj.address_string
0,278399,Hotel Cristal Bialystok,Białystok,3 Lipowa Street,NaN,Bialystok,Podlaskie Province,Poland,15-424,"3 Lipowa Street, Bialystok 15-424 Poland"
1,10050636,Ibis Styles Bialystok,Białystok,Aleja Pilsudskiego 25,NaN,Bialystok,Podlaskie Province,Poland,15-444,"Aleja Pilsudskiego 25, Bialystok 15-444 Poland"
2,23643711,Hampton by Hilton Bialystok,Białystok,2 Wislawy Szymborskiej,NaN,Bialystok,Podlaskie Province,Poland,15-424,"2 Wislawy Szymborskiej, Bialystok 15-424 Poland"
3,21356073,Mercure Bialystok,Białystok,Hetmanska 46,NaN,Bialystok,Podlaskie Province,Poland,15-727,"Hetmanska 46, Bialystok 15-727 Poland"
4,23247934,Hostel Bialystok Centrum,Białystok,Ks. Adama Abramowicza 2,NaN,Bialystok,Podlaskie Province,Poland,15-872,"Ks. Adama Abramowicza 2, Bialystok 15-872 Poland"

In [8]:
df['query_city'] = (
    df['query_city']
    .apply(unidecode)
)
df.head(5)

,location_id,name,query_city,address_obj.street1,address_obj.street2,address_obj.city,address_obj.state,address_obj.country,address_obj.postalcode,address_obj.address_string
0,278399,Hotel Cristal Bialystok,Bialystok,3 Lipowa Street,NaN,Bialystok,Podlaskie Province,Poland,15-424,"3 Lipowa Street, Bialystok 15-424 Poland"
1,10050636,Ibis Styles Bialystok,Bialystok,Aleja Pilsudskiego 25,NaN,Bialystok,Podlaskie Province,Poland,15-444,"Aleja Pilsudskiego 25, Bialystok 15-444 Poland"
2,23643711,Hampton by Hilton Bialystok,Bialystok,2 Wislawy Szymborskiej,NaN,Bialystok,Podlaskie Province,Poland,15-424,"2 Wislawy Szymborskiej, Bialystok 15-424 Poland"
3,21356073,Mercure Bialystok,Bialystok,Hetmanska 46,NaN,Bialystok,Podlaskie Province,Poland,15-727,"Hetmanska 46, Bialystok 15-727 Poland"
4,23247934,Hostel Bialystok Centrum,Bialystok,Ks. Adama Abramowicza 2,NaN,Bialystok,Podlaskie Province,Poland,15-872,"Ks. Adama Abramowicza 2, Bialystok 15-872 Poland"

In [9]:
df = df[df["query_city"] == df['address_obj.city']]

In [10]:
df.to_csv("hotele.csv", index=False)

In [ ]:
df = pd.read_csv("reviews_raw.csv")
df.head(10)

,id,lang,location_id,published_date,rating,helpful_votes,rating_image_url,url,text,title,...,subratings.3.localized_name,subratings.4.name,subratings.4.rating_image_url,subratings.4.value,subratings.4.localized_name,subratings.5.name,subratings.5.rating_image_url,subratings.5.value,subratings.5.localized_name,user.user_location.name
0,1029040227,en,278399,2025-09-06T07:57:42Z,5,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,Great place to stay. Room was very large and w...,Central Location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1028901978,en,278399,2025-09-05T09:34:55Z,1,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,I came to eat a delicious Provençal soup and a...,Słaba obsługa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1021148887,en,278399,2025-07-27T13:21:27Z,1,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,I've try to call them 3 times and each time I'...,Not nice,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1033812883,en,10050636,2025-10-07T10:16:23Z,5,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,This was my second time in a suite. 100% recom...,Just book it! Great hotel!,...,Cleanliness,RATE_SERVICE,https://www.tripadvisor.com/img/cdsi/img2/rati...,5.0,Service,RATE_SLEEP,https://www.tripadvisor.com/img/cdsi/img2/rati...,4.0,Sleep Quality,NaN
4,1019523151,en,10050636,2025-07-20T03:03:09Z,4,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,This hotel is in a great location. Attached to...,Good location in Bialystock,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Melbourne, Victoria"
5,972191134,en,10050636,2024-10-01T15:45:27Z,3,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,The hotel was easy to find this the parking pl...,Ok,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sweden
6,953043053,en,10050636,2024-05-30T14:46:34Z,5,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,"Cool location, near the city center, very nice...",Cool Location,...,Cleanliness,RATE_SERVICE,https://www.tripadvisor.com/img/cdsi/img2/rati...,5.0,Service,RATE_SLEEP,https://www.tripadvisor.com/img/cdsi/img2/rati...,5.0,Sleep Quality,Vienna
7,1058816082,en,23643711,2026-05-03T11:34:22Z,5,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,What a surprise to find this venue. Near all ...,Central Europe is a cool place to visit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Amherst, New Hampshire"
8,1055109917,en,23643711,2026-04-02T10:48:48Z,1,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,At check out no invoice was issued in either p...,No invoice,...,Cleanliness,RATE_SERVICE,https://www.tripadvisor.com/img/cdsi/img2/rati...,1.0,Service,RATE_SLEEP,https://www.tripadvisor.com/img/cdsi/img2/rati...,1.0,Sleep Quality,"Milan, Lombardy"
9,1019028526,en,23643711,2025-07-17T05:14:47Z,5,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,We stayed at this hotel on the recommendation ...,Highly Recommended Hotel,...,Cleanliness,RATE_SERVICE,https://www.tripadvisor.com/img/cdsi/img2/rati...,5.0,Service,RATE_SLEEP,https://www.tripadvisor.com/img/cdsi/img2/rati...,5.0,Sleep Quality,"Malvern, Pennsylvania"

In [13]:
df['location_id']

0        278399
1        278399
2        278399
3      10050636
4      10050636
         ...
463     7103076
464     7103076
465     6583918
466     6583918
467     8342267
Name: location_id, Length: 468, dtype: int64

In [20]:
x = df.groupby('location_id')
x.groups.keys()

dict_keys([275076, 275077, 275079, 275082, 275085, 275087, 277358, 277359, 277622, 277623, 277624, 277626, 277647, 277649, 277656, 277663, 278399, 284634, 285471, 286780, 287051, 321158, 502269, 505389, 528365, 528494, 528501, 609368, 624748, 626806, 641571, 651618, 652453, 779781, 953906, 1015711, 1072730, 1109745, 1400018, 1458515, 1462729, 1507917, 1519907, 1654292, 1723757, 1728175, 1729285, 1735518, 1743726, 1754683, 1757360, 1757685, 1776883, 1885452, 2082637, 2160071, 2254821, 2269524, 2482444, 2489753, 2508570, 3343284, 3485588, 3595685, 3645102, 4011143, 4176964, 4427782, 4557505, 4579828, 4603321, 4888442, 4932574, 5521691, 6523226, 6583918, 6664499, 6998708, 7103076, 7179861, 7332037, 7394519, 7625450, 7710716, 7780556, 8342267, 8387269, 8704659, 9763242, 9808341, 9884047, 10050636, 10267423, 10470842, 11622060, 11680364, 12000203, 12167331, 12246671, 12393367, 12431905, 12553141, 13228421, 14040909, 14055281, 14167696, 14958792, 14989391, 15243198, 15676982, 16830226, 17165609, 17338497, 17634606, 17649381, 19896334, 20088530, 20935494, 21164553, 21356073, 23247934, 23391245, 23417081, 23495914, 23518362, 23643711, 24923696, 26308453])

In [22]:
x.get_group(275076)

,id,lang,location_id,published_date,rating,helpful_votes,rating_image_url,url,text,title,...,subratings.3.localized_name,subratings.4.name,subratings.4.rating_image_url,subratings.4.value,subratings.4.localized_name,subratings.5.name,subratings.5.rating_image_url,subratings.5.value,subratings.5.localized_name,user.user_location.name
116,1057262250,en,275076,2026-04-20T10:40:13Z,4,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,"The rooms here are surprisingly spacious, clea...",Everything great except one thing,...,Cleanliness,RATE_SERVICE,https://www.tripadvisor.com/img/cdsi/img2/rati...,5.0,Service,RATE_SLEEP,https://www.tripadvisor.com/img/cdsi/img2/rati...,1.0,Sleep Quality,"Cambridge, Cambridgeshire, England"
117,1043744409,en,275076,2025-12-26T10:06:43Z,5,0,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,Located a short walk from the Central Railway ...,An Excellent Stay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Sydney, New South Wales"
118,1023824954,en,275076,2025-08-11T12:21:28Z,5,1,https://www.tripadvisor.com/img/cdsi/img2/rati...,https://www.tripadvisor.com/ShowUserReviews-g2...,We stayed at Novotel Poznań Centrum for the fi...,Great location,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Riga, Riga Region"

In [26]:
for location_id, group in x:
    print(location_id)
    a = group.head()
    print(a['rating'])

275076
116    4
117    5
118    5
Name: rating, dtype: int64
275077
127    5
128    2
129    2
130    5
Name: rating, dtype: int64
275079
112    5
113    5
114    5
115    5
Name: rating, dtype: int64
275082
241    4
242    3
Name: rating, dtype: int64
275085
197    5
198    4
199    5
200    5
201    4
Name: rating, dtype: int64
275087
172    2
173    5
Name: rating, dtype: int64
277358
66    2
67    4
68    5
Name: rating, dtype: int64
277359
61    4
62    5
63    5
64    4
65    4
Name: rating, dtype: int64
277622
313    4
314    5
315    1
316    5
Name: rating, dtype: int64
277623
322    4
323    4
Name: rating, dtype: int64
277624
324    5
325    4
326    5
327    5
328    4
Name: rating, dtype: int64
277626
309    5
310    5
311    5
312    3
Name: rating, dtype: int64
277647
187    5
188    4
189    5
Name: rating, dtype: int64
277649
69    5
70    4
71    5
72    5
Name: rating, dtype: int64
277656
136    5
137    5
138    5
139    5
140    2
Name: rating, dtype: int64
277663
390    2
391    4
392    5
Name: rating, dtype: int64
278399
0    5
1    1
2    1
Name: rating, dtype: int64
284634
334    1
335    1
Name: rating, dtype: int64
285471
218    5
219    5
220    5
221    5
222    5
Name: rating, dtype: int64
286780
94    5
95    5
96    5
97    5
98    4
Name: rating, dtype: int64
287051
261    3
262    5
263    4
264    5
Name: rating, dtype: int64
321158
31    4
32    5
33    5
34    5
35    5
Name: rating, dtype: int64
502269
85    5
86    5
Name: rating, dtype: int64
505389
402    1
403    1
404    1
405    4
Name: rating, dtype: int64
528365
285    5
286    3
287    4
288    4
289    4
Name: rating, dtype: int64
528494
278    4
279    5
Name: rating, dtype: int64
528501
25    4
26    5
27    4
Name: rating, dtype: int64
609368
49    5
50    5
51    4
52    5
53    5
Name: rating, dtype: int64
624748
420    2
421    5
422    5
423    5
424    3
Name: rating, dtype: int64
626806
103    5
104    5
105    5
106    1
107    5
Name: rating, dtype: int64
641571
18    5
19    5
20    5
21    5
22    4
Name: rating, dtype: int64
651618
223    4
224    5
225    5
Name: rating, dtype: int64
652453
125    5
126    5
Name: rating, dtype: int64
779781
174    5
175    4
Name: rating, dtype: int64
953906
153    3
154    5
155    4
156    5
Name: rating, dtype: int64
1015711
202    5
203    2
204    5
Name: rating, dtype: int64
1072730
108    5
109    5
110    5
111    5
Name: rating, dtype: int64
1109745
190    5
191    4
192    5
193    5
Name: rating, dtype: int64
1400018
75    5
76    5
Name: rating, dtype: int64
1458515
243    1
Name: rating, dtype: int64
1462729
247    5
248    5
249    5
250    4
Name: rating, dtype: int64
1507917
457    1
458    5
459    4
460    5
461    5
Name: rating, dtype: int64
1519907
230    1
231    3
232    5
Name: rating, dtype: int64
1654292
73    5
74    4
Name: rating, dtype: int64
1723757
87    2
88    4
89    4
90    1
Name: rating, dtype: int64
1728175
57    4
58    5
59    5
60    5
Name: rating, dtype: int64
1729285
440    4
441    3
442    1
443    3
Name: rating, dtype: int64
1735518
435    5
436    4
437    1
438    3
439    1
Name: rating, dtype: int64
1743726
393    1
394    5
Name: rating, dtype: int64
1754683
168    4
169    5
170    5
171    5
Name: rating, dtype: int64
1757360
430    4
431    1
432    2
433    4
434    5
Name: rating, dtype: int64
1757685
244    5
245    3
246    4
Name: rating, dtype: int64
1776883
362    5
363    4
364    5
365    5
366    5
Name: rating, dtype: int64
1885452
251    5
252    5
253    3
254    5
255    4
Name: rating, dtype: int64
2082637
306    5
307    5
308    5
Name: rating, dtype: int64
2160071
452    3
453    4
454    4
455    1
456    4
Name: rating, dtype: int64
2254821
265    5
266    5
267    1
Name: rating, dtype: int64
2269524
226    5
227    3
228    5
229    5
Name: rating, dtype: int64
2482444
444    1
445    5
446    5
447    4
448    5
Name: rating, dtype: int64
2489753
358    5
359    4
360    3
361    4
Name: rating, dtype: int64
2508570
209    5
210    5
211    5
212    4
213    5
Name: rating, dtype: int64
3343284
237    5
238    2
239    3
240    5
Name: rating, dtype: int64
3485588
372    1
373    5
374    4
375    5
Name: rating, dtype: int64
3595685
296    4
297    3
298    4
299    3
300    3
Name: rating, dtype: int64
3645102
413    5
414    4
415    2
416    5
Name: rating, dtype: int64
4011143
336    5
337    5
338    5
339    4
Name: rating, dtype: int64
4176964
54    5
55    5
56    5
Name: rating, dtype: int64
4427782
273    4
274    5
275    5
276    4
277    5
Name: rating, dtype: int64
4557505
344    5
345    5
346    1
347    1
348    4
Name: rating, dtype: int64
4579828
367    5
368    1
369    1
370    4
371    5
Name: rating, dtype: int64
4603321
280    3
281    3
282    1
283    3
284    2
Name: rating, dtype: int64
4888442
157    5
158    4
159    4
160    4
161    5
Name: rating, dtype: int64
4932574
349    2
350    4
351    4
352    4
353    4
Name: rating, dtype: int64
5521691
354    5
355    4
356    2
357    1
Name: rating, dtype: int64
6523226
449    1
450    5
451    5
Name: rating, dtype: int64
6583918
465    5
466    5
Name: rating, dtype: int64
6664499
99     5
100    5
101    5
102    5
Name: rating, dtype: int64
6998708
146    3
147    2
148    5
149    5
Name: rating, dtype: int64
7103076
463    5
464    5
Name: rating, dtype: int64
7179861
268    4
269    5
270    5
271    3
272    5
Name: rating, dtype: int64
7332037
387    5
388    5
389    5
Name: rating, dtype: int64
7394519
163    4
164    5
165    5
166    5
167    5
Name: rating, dtype: int64
7625450
425    5
426    4
427    5
428    5
429    5
Name: rating, dtype: int64
7710716
162    5
Name: rating, dtype: int64
7780556
141    5
142    5
143    5
144    5
145    4
Name: rating, dtype: int64
8342267
467    5
Name: rating, dtype: int64
8387269
340    5
341    5
342    5
343    2
Name: rating, dtype: int64
8704659
406    5
407    4
408    5
409    5
Name: rating, dtype: int64
9763242
332    1
333    3
Name: rating, dtype: int64
9808341
383    5
384    4
385    3
386    4
Name: rating, dtype: int64
9884047
36    5
37    5
38    4
39    5
40    5
Name: rating, dtype: int64
10050636
3    5
4    4
5    3
6    5
Name: rating, dtype: int64
10267423
317    5
318    5
319    5
320    5
321    5
Name: rating, dtype: int64
10470842
214    5
215    1
216    5
217    2
Name: rating, dtype: int64
11622060
462    5
Name: rating, dtype: int64
11680364
23    5
24    1
Name: rating, dtype: int64
12000203
395    5
396    5
397    5
Name: rating, dtype: int64
12167331
77    4
78    4
79    2
Name: rating, dtype: int64
12246671
91    5
92    5
93    5
Name: rating, dtype: int64
12393367
41    5
42    5
43    5
44    5
45    2
Name: rating, dtype: int64
12431905
256    4
257    3
258    4
259    5
260    4
Name: rating, dtype: int64
12553141
329    1
330    5
331    4
Name: rating, dtype: int64
13228421
233    5
234    3
235    5
236    1
Name: rating, dtype: int64
14040909
28    5
29    5
30    5
Name: rating, dtype: int64
14055281
176    5
177    5
178    5
Name: rating, dtype: int64
14167696
179    5
180    5
181    5
Name: rating, dtype: int64
14958792
131    5
132    4
133    2
134    1
135    4
Name: rating, dtype: int64
14989391
119    4
120    3
121    5
Name: rating, dtype: int64
15243198
122    3
123    5
124    5
Name: rating, dtype: int64
15676982
182    5
183    5
184    1
185    5
186    5
Name: rating, dtype: int64
16830226
194    5
195    5
196    5
Name: rating, dtype: int64
17165609
379    5
380    5
381    2
382    5
Name: rating, dtype: int64
17338497
302    5
303    5
304    5
305    5
Name: rating, dtype: int64
17634606
410    2
411    5
412    5
Name: rating, dtype: int64
17649381
417    5
418    5
419    5
Name: rating, dtype: int64
19896334
301    3
Name: rating, dtype: int64
20088530
376    5
377    5
378    5
Name: rating, dtype: int64
20935494
205    5
206    5
207    5
208    5
Name: rating, dtype: int64
21164553
398    1
399    1
400    1
401    5
Name: rating, dtype: int64
21356073
12    5
13    1
14    4
Name: rating, dtype: int64
23247934
15    5
16    4
17    4
Name: rating, dtype: int64
23391245
46    5
47    5
48    5
Name: rating, dtype: int64
23417081
80    5
81    5
82    5
83    3
84    4
Name: rating, dtype: int64
23495914
292    5
293    5
294    5
295    5
Name: rating, dtype: int64
23518362
152    5
Name: rating, dtype: int64
23643711
7     5
8     1
9     5
10    4
11    4
Name: rating, dtype: int64
24923696
290    5
291    5
Name: rating, dtype: int64
26308453
150    5
151    5
Name: rating, dtype: int64

In [27]:
df.columns

Index(['id', 'lang', 'location_id', 'published_date', 'rating',
       'helpful_votes', 'rating_image_url', 'url', 'text', 'title',
       'trip_type', 'travel_date', 'user.username', 'user.user_location.id',
       'user.avatar.thumbnail', 'user.avatar.small', 'user.avatar.medium',
       'user.avatar.large', 'user.avatar.original', 'owner_response.id',
       'owner_response.title', 'owner_response.text', 'owner_response.lang',
       'owner_response.author', 'owner_response.published_date',
       'subratings.0.name', 'subratings.0.rating_image_url',
       'subratings.0.value', 'subratings.0.localized_name',
       'subratings.1.name', 'subratings.1.rating_image_url',
       'subratings.1.value', 'subratings.1.localized_name',
       'subratings.2.name', 'subratings.2.rating_image_url',
       'subratings.2.value', 'subratings.2.localized_name',
       'subratings.3.name', 'subratings.3.rating_image_url',
       'subratings.3.value', 'subratings.3.localized_name',
       'subratings.4.name', 'subratings.4.rating_image_url',
       'subratings.4.value', 'subratings.4.localized_name',
       'subratings.5.name', 'subratings.5.rating_image_url',
       'subratings.5.value', 'subratings.5.localized_name',
       'user.user_location.name'],
      dtype='object')

In [31]:
df['rating_image_url']

0      https://www.tripadvisor.com/img/cdsi/img2/rati...
1      https://www.tripadvisor.com/img/cdsi/img2/rati...
2      https://www.tripadvisor.com/img/cdsi/img2/rati...
3      https://www.tripadvisor.com/img/cdsi/img2/rati...
4      https://www.tripadvisor.com/img/cdsi/img2/rati...
                             ...
463    https://www.tripadvisor.com/img/cdsi/img2/rati...
464    https://www.tripadvisor.com/img/cdsi/img2/rati...
465    https://www.tripadvisor.com/img/cdsi/img2/rati...
466    https://www.tripadvisor.com/img/cdsi/img2/rati...
467    https://www.tripadvisor.com/img/cdsi/img2/rati...
Name: rating_image_url, Length: 468, dtype: object

In [73]:
df.drop(columns=[
    "helpful_votes",'rating_image_url', 'user.avatar.thumbnail', 
    'user.avatar.small', 'user.avatar.medium', 'user.avatar.large', 
    'user.avatar.original', "subratings.0.rating_image_url", 
    "subratings.1.rating_image_url", "subratings.2.rating_image_url",
    "subratings.3.rating_image_url", "subratings.4.rating_image_url",
    "subratings.5.rating_image_url",
    # systemowa nazwa ratingu:
    "subratings.1.name", "subratings.2.name",
    "subratings.3.name", "subratings.4.name",
    "subratings.5.name",
    # wszystko jest w en:
    'lang',
    # url nie potrzebne:
    'url',
], inplace=True, errors='ignore')
df.columns

Index(['id', 'location_id', 'published_date', 'rating', 'text', 'title',
       'trip_type', 'travel_date', 'user.username', 'user.user_location.id',
       'owner_response.id', 'owner_response.title', 'owner_response.text',
       'owner_response.lang', 'owner_response.author',
       'owner_response.published_date', 'subratings.0.name',
       'subratings.0.value', 'subratings.0.localized_name',
       'subratings.1.value', 'subratings.1.localized_name',
       'subratings.2.value', 'subratings.2.localized_name',
       'subratings.3.value', 'subratings.3.localized_name',
       'subratings.4.value', 'subratings.4.localized_name',
       'subratings.5.value', 'subratings.5.localized_name',
       'user.user_location.name'],
      dtype='object')

In [74]:
print(f"""
{df.shape}, 
{df['subratings.0.value'].value_counts()} 
{df['subratings.1.value'].value_counts()} 
{df['subratings.2.value'].value_counts()} 
{df['subratings.3.value'].value_counts()}
{df['subratings.4.value'].value_counts()}
{df['subratings.5.value'].value_counts()}
""")

(468, 30),
subratings.0.value
5.0    114
4.0     56
3.0     20
1.0     18
2.0      8
Name: count, dtype: int64
subratings.1.value
5.0    117
4.0     60
3.0     16
1.0     16
2.0      6
Name: count, dtype: int64
subratings.2.value
5.0    143
4.0     43
3.0     13
1.0      8
2.0      5
Name: count, dtype: int64
subratings.3.value
5.0    97
4.0    25
3.0     8
2.0     6
1.0     5
Name: count, dtype: int64
subratings.4.value
5.0    90
1.0    16
4.0    16
3.0    12
2.0     5
Name: count, dtype: int64
subratings.5.value
5.0    78
4.0    31
1.0    12
3.0     8
2.0     6
Name: count, dtype: int64

In [76]:
df.to_csv("reviews.csv", index=False)
df.head(1)

,id,location_id,published_date,rating,text,title,trip_type,travel_date,user.username,user.user_location.id,...,subratings.1.localized_name,subratings.2.value,subratings.2.localized_name,subratings.3.value,subratings.3.localized_name,subratings.4.value,subratings.4.localized_name,subratings.5.value,subratings.5.localized_name,user.user_location.name
0,1029040227,278399,2025-09-06T07:57:42Z,5,Great place to stay. Room was very large and w...,Central Location,Couples,2025-08-31,ellenp667,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:

df = pd.read_csv("details_raw.csv")
df.head(2)

,location_id,name,web_url,ancestors,latitude,longitude,timezone,write_review,rating,rating_image_url,...,subratings.5.rating_image_url,subratings.5.value,hours.periods,hours.weekday_text,category.name,category.localized_name,parent_brand,brand,description,phone
0,278399,Hotel Cristal Bialystok,https://www.tripadvisor.com/Hotel_Review-g2747...,"[{'level': 'City', 'name': 'Bialystok', 'locat...",53.132675,23.155990,Europe/Warsaw,https://www.tripadvisor.com/UserReview-g274741...,4.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,https://static.tacdn.com/img2/ratings/traveler...,4.6,"[{'open': {'day': 1, 'time': '0000'}, 'close':...","['Monday: 00:00 - 00:00', 'Tuesday: 00:00 - 00...",hotel,Hotel,NaN,NaN,NaN,NaN
1,10050636,Ibis Styles Bialystok,https://www.tripadvisor.com/Hotel_Review-g2747...,"[{'level': 'City', 'name': 'Bialystok', 'locat...",53.136300,23.162004,Europe/Warsaw,https://www.tripadvisor.com/UserReview-g274741...,4.5,https://www.tripadvisor.com/img/cdsi/img2/rati...,...,https://static.tacdn.com/img2/ratings/traveler...,4.8,NaN,NaN,hotel,Hotel,Accor,ibis Styles,NaN,NaN

In [78]:
df.columns

Index(['location_id', 'name', 'web_url', 'ancestors', 'latitude', 'longitude',
       'timezone', 'write_review', 'rating', 'rating_image_url', 'num_reviews',
       'photo_count', 'see_all_photos', 'price_level', 'amenities',
       'subcategory', 'styles', 'neighborhood_info', 'trip_types', 'awards',
       'address_obj.street1', 'address_obj.street2', 'address_obj.city',
       'address_obj.state', 'address_obj.country', 'address_obj.postalcode',
       'address_obj.address_string', 'ranking_data.geo_location_id',
       'ranking_data.ranking_string', 'ranking_data.geo_location_name',
       'ranking_data.ranking_out_of', 'ranking_data.ranking',
       'review_rating_count.1', 'review_rating_count.2',
       'review_rating_count.3', 'review_rating_count.4',
       'review_rating_count.5', 'subratings.0.name',
       'subratings.0.localized_name', 'subratings.0.rating_image_url',
       'subratings.0.value', 'subratings.1.name',
       'subratings.1.localized_name', 'subratings.1.rating_image_url',
       'subratings.1.value', 'subratings.2.name',
       'subratings.2.localized_name', 'subratings.2.rating_image_url',
       'subratings.2.value', 'subratings.3.name',
       'subratings.3.localized_name', 'subratings.3.rating_image_url',
       'subratings.3.value', 'subratings.4.name',
       'subratings.4.localized_name', 'subratings.4.rating_image_url',
       'subratings.4.value', 'subratings.5.name',
       'subratings.5.localized_name', 'subratings.5.rating_image_url',
       'subratings.5.value', 'hours.periods', 'hours.weekday_text',
       'category.name', 'category.localized_name', 'parent_brand', 'brand',
       'description', 'phone'],
      dtype='object')

In [ ]:
df.drop(columns=[
    "helpful_votes",'rating_image_url', 'user.avatar.thumbnail', 
    'user.avatar.small', 'user.avatar.medium', 'user.avatar.large', 
    'user.avatar.original', "subratings.0.rating_image_url", 
    "subratings.1.rating_image_url", "subratings.2.rating_image_url",
    "subratings.3.rating_image_url", "subratings.4.rating_image_url",
    "subratings.5.rating_image_url",
    # systemowa nazwa ratingu:
    "subratings.1.name", "subratings.2.name",
    "subratings.3.name", "subratings.4.name",
    "subratings.5.name",
    # wszystko jest w en:
    'lang',
    # url nie potrzebne:
    'url',
    # dla details:
    "rating_image_url","web_url",'ancestors',
    'photo_count', "see_all_photos",
], inplace=True, errors='ignore')
df.columns

Index(['location_id', 'name', 'latitude', 'longitude', 'timezone',
       'write_review', 'rating', 'num_reviews', 'see_all_photos',
       'price_level', 'amenities', 'subcategory', 'styles',
       'neighborhood_info', 'trip_types', 'awards', 'address_obj.street1',
       'address_obj.street2', 'address_obj.city', 'address_obj.state',
       'address_obj.country', 'address_obj.postalcode',
       'address_obj.address_string', 'ranking_data.geo_location_id',
       'ranking_data.ranking_string', 'ranking_data.geo_location_name',
       'ranking_data.ranking_out_of', 'ranking_data.ranking',
       'review_rating_count.1', 'review_rating_count.2',
       'review_rating_count.3', 'review_rating_count.4',
       'review_rating_count.5', 'subratings.0.name',
       'subratings.0.localized_name', 'subratings.0.value',
       'subratings.1.localized_name', 'subratings.1.value',
       'subratings.2.localized_name', 'subratings.2.value',
       'subratings.3.localized_name', 'subratings.3.value',
       'subratings.4.localized_name', 'subratings.4.value',
       'subratings.5.localized_name', 'subratings.5.value', 'hours.periods',
       'hours.weekday_text', 'category.name', 'category.localized_name',
       'parent_brand', 'brand', 'description', 'phone'],
      dtype='object')

In [86]:
print(f"""
{df.shape}, 
{df['hours.periods'].value_counts()} 
""")

(135, 54),
hours.periods
[{'open': {'day': 1, 'time': '0000'}, 'close': {'day': 1, 'time': '0000'}}, {'open': {'day': 2, 'time': '0000'}, 'close': {'day': 2, 'time': '0000'}}, {'open': {'day': 3, 'time': '0000'}, 'close': {'day': 3, 'time': '0000'}}, {'open': {'day': 4, 'time': '0000'}, 'close': {'day': 4, 'time': '0000'}}, {'open': {'day': 5, 'time': '0000'}, 'close': {'day': 5, 'time': '0000'}}, {'open': {'day': 6, 'time': '0000'}, 'close': {'day': 6, 'time': '0000'}}, {'open': {'day': 7, 'time': '0000'}, 'close': {'day': 7, 'time': '0000'}}]    18
Name: count, dtype: int64

In [61]:
import pandas as pd
x = pd.read_csv('hotele_raw.csv')
y = pd.read_csv('reviews_raw.csv') 
z = pd.read_csv('details_raw.csv')

print(f"""
hotele: ({x.shape}) {x.columns} \n\n
reviews: ({y.shape}) {y.columns} \n\n
details: ({z.shape}) {z.columns} \n\n
""")

hotele: ((150, 10)) Index(['location_id', 'name', 'query_city', 'address_obj.street1',
       'address_obj.street2', 'address_obj.city', 'address_obj.state',
       'address_obj.country', 'address_obj.postalcode',
       'address_obj.address_string'],
      dtype='object')


reviews: ((468, 50)) Index(['id', 'lang', 'location_id', 'published_date', 'rating',
       'helpful_votes', 'rating_image_url', 'url', 'text', 'title',
       'trip_type', 'travel_date', 'user.username', 'user.user_location.id',
       'user.avatar.thumbnail', 'user.avatar.small', 'user.avatar.medium',
       'user.avatar.large', 'user.avatar.original', 'owner_response.id',
       'owner_response.title', 'owner_response.text', 'owner_response.lang',
       'owner_response.author', 'owner_response.published_date',
       'subratings.0.name', 'subratings.0.rating_image_url',
       'subratings.0.value', 'subratings.0.localized_name',
       'subratings.1.name', 'subratings.1.rating_image_url',
       'subratings.1.value', 'subratings.1.localized_name',
       'subratings.2.name', 'subratings.2.rating_image_url',
       'subratings.2.value', 'subratings.2.localized_name',
       'subratings.3.name', 'subratings.3.rating_image_url',
       'subratings.3.value', 'subratings.3.localized_name',
       'subratings.4.name', 'subratings.4.rating_image_url',
       'subratings.4.value', 'subratings.4.localized_name',
       'subratings.5.name', 'subratings.5.rating_image_url',
       'subratings.5.value', 'subratings.5.localized_name',
       'user.user_location.name'],
      dtype='object')


details: ((135, 69)) Index(['location_id', 'name', 'web_url', 'ancestors', 'latitude', 'longitude',
       'timezone', 'write_review', 'rating', 'rating_image_url', 'num_reviews',
       'photo_count', 'see_all_photos', 'price_level', 'amenities',
       'subcategory', 'styles', 'neighborhood_info', 'trip_types', 'awards',
       'address_obj.street1', 'address_obj.street2', 'address_obj.city',
       'address_obj.state', 'address_obj.country', 'address_obj.postalcode',
       'address_obj.address_string', 'ranking_data.geo_location_id',
       'ranking_data.ranking_string', 'ranking_data.geo_location_name',
       'ranking_data.ranking_out_of', 'ranking_data.ranking',
       'review_rating_count.1', 'review_rating_count.2',
       'review_rating_count.3', 'review_rating_count.4',
       'review_rating_count.5', 'subratings.0.name',
       'subratings.0.localized_name', 'subratings.0.rating_image_url',
       'subratings.0.value', 'subratings.1.name',
       'subratings.1.localized_name', 'subratings.1.rating_image_url',
       'subratings.1.value', 'subratings.2.name',
       'subratings.2.localized_name', 'subratings.2.rating_image_url',
       'subratings.2.value', 'subratings.3.name',
       'subratings.3.localized_name', 'subratings.3.rating_image_url',
       'subratings.3.value', 'subratings.4.name',
       'subratings.4.localized_name', 'subratings.4.rating_image_url',
       'subratings.4.value', 'subratings.5.name',
       'subratings.5.localized_name', 'subratings.5.rating_image_url',
       'subratings.5.value', 'hours.periods', 'hours.weekday_text',
       'category.name', 'category.localized_name', 'parent_brand', 'brand',
       'description', 'phone'],
      dtype='object')

In [62]:
# =========================================
# HOTELE
# =========================================

x_keep = [
    "location_id",
    "name",
    # "query_city",
    "address_obj.city",
    "address_obj.state",
    # "address_obj.country",
]

x = x[[col for col in x_keep if col in x.columns]]


# =========================================
# REVIEWS
# =========================================

y_keep = [
    "id",
    "location_id",
    "published_date",
    "rating",
    "helpful_votes",
    "text",
    "title",
    "trip_type",
    "travel_date",
    "user.username",
    "user.user_location.name",
    
    'owner_response.title', 'owner_response.text',
    'owner_response.author', 'owner_response.published_date',
    
    "subratings.0.localized_name","subratings.0.value",
    "subratings.1.localized_name","subratings.1.value",
    "subratings.2.localized_name","subratings.2.value",
    "subratings.3.localized_name","subratings.3.value",
    "subratings.4.localized_name","subratings.4.value",
    "subratings.5.localized_name","subratings.5.value",
]

y = y[[col for col in y_keep if col in y.columns]]


# =========================================
# DETAILS
# =========================================

z_keep = [
    "location_id",
    "name",
    "latitude",
    "longitude",
    "rating",
    "num_reviews",
    "photo_count",
    "price_level",
    "amenities",
    "styles",
    "trip_types",
    "address_obj.city",
    "address_obj.country",
    "ranking_data.ranking_out_of",
    "ranking_data.ranking",
    "review_rating_count.1",
    "review_rating_count.2",
    "review_rating_count.3",
    "review_rating_count.4",
    "review_rating_count.5",
    # "category.localized_name",
    "brand",
    "description",
    "subratings.0.localized_name","subratings.0.value",
    "subratings.1.localized_name","subratings.1.value",
    "subratings.2.localized_name","subratings.2.value",
    "subratings.3.localized_name","subratings.3.value",
    "subratings.4.localized_name","subratings.4.value",
    "subratings.5.localized_name","subratings.5.value",
]

z = z[[col for col in z_keep if col in z.columns]]

In [63]:
import os
os.makedirs('data', exist_ok=True)

In [64]:
x.to_csv("data/hotele_clear.csv", index=False)
x.head(2)

   location_id                     name address_obj.city   address_obj.state
0       278399  Hotel Cristal Bialystok        Bialystok  Podlaskie Province
1     10050636    Ibis Styles Bialystok        Bialystok  Podlaskie Province

In [65]:
y.to_csv("data/reviews_clean.csv", index=False)
y.head(2)

,id,location_id,published_date,rating,helpful_votes,text,title,trip_type,travel_date,user.username,...,subratings.1.localized_name,subratings.1.value,subratings.2.localized_name,subratings.2.value,subratings.3.localized_name,subratings.3.value,subratings.4.localized_name,subratings.4.value,subratings.5.localized_name,subratings.5.value
0,1029040227,278399,2025-09-06T07:57:42Z,5,0,Great place to stay. Room was very large and w...,Central Location,Couples,2025-08-31,ellenp667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1028901978,278399,2025-09-05T09:34:55Z,1,0,I came to eat a delicious Provençal soup and a...,Słaba obsługa,Solo travel,2025-09-30,Departure58486761593,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
z.to_csv("data/details.csv", index=False)
z.head(2)

,location_id,name,latitude,longitude,rating,num_reviews,photo_count,price_level,amenities,styles,...,subratings.1.localized_name,subratings.1.value,subratings.2.localized_name,subratings.2.value,subratings.3.localized_name,subratings.3.value,subratings.4.localized_name,subratings.4.value,subratings.5.localized_name,subratings.5.value
0,278399,Hotel Cristal Bialystok,53.132675,23.155990,4.5,390,221,$,"['Internet', 'Suites', 'Room service', 'Free I...","['Modern', 'Classic']",...,Sleep Quality,4.3,Rooms,4.3,Service,4.7,Value,4.3,Cleanliness,4.6
1,10050636,Ibis Styles Bialystok,53.136300,23.162004,4.5,375,302,$,"['Internet', 'Kids Activities', 'Suites', 'Roo...","['Modern', 'Mid-range']",...,Sleep Quality,4.7,Rooms,4.6,Service,4.6,Value,4.5,Cleanliness,4.8

In [67]:
import os

test_x = x.head()
test_y = y.head()
test_z = z.head()

os.makedirs('test/clean', exist_ok=True)

test_x.to_csv('test/clean/hotele_test.csv', index=False)
test_y.to_csv('test/clean/reviews_test.csv', index=False)
test_z.to_csv('test/clean/details_test.csv', index=False)

In [68]:
hotels_full = x.merge(
    z,
    on="location_id",
    how="left",
    suffixes=("_search", "_details")
)

hotels_full.to_csv("data/hotels_full.csv", index=False, encoding="utf-8-sig")

In [69]:
hotels_full = hotels_full.drop(columns=[
    "name_search",
    "address_obj.city_search",
    "address_obj.country_search"
], errors="ignore")

In [70]:
hotels_full_test = hotels_full.head()
hotels_full_test.to_csv("test/clean/hotels_full.csv", index=False)

In [ ]:
os.makedirs('data/full', exist_ok=True)

hotels_full.to_csv("data/full/hotels.csv", index=False, encoding="utf-8-sig")
y.to_csv('data/full/reviews.csv', index=False, encoding="utf-8-sig")